test: test.cpp
	g++ test.cpp -o test -lgmp -lgmpxx
rsa: p5_rsa.cpp
	g++ p5_rsa.cpp -o p5_rsa -lgmp -lgmpxx
p6: p6_qpow.cpp
	g++ p6_qpow.cpp -o p6_qpow -lgmp -lgmpxx
p7: p7_china.cpp
	g++ p7_china.cpp -o p7_china -lgmp -lgmpxx

	

